Resources:
  LB8A12904C:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes: []
      Scheme: internal
      Subnets:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ","
                - Fn::ImportValue: Vpc:TheVPCPrivateSubnetIDsE53B48B1
      Type: network
    Metadata:
      aws:cdk:path: NLB/LB/Resource
  LBapi1listenerAAC7334B:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi1listenerECSGroupB9F61AC8
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 2000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api1_listener/Resource
  LBapi1listenerECSGroupB9F61AC8:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: ip
      VpcId:
        Fn::ImportValue: Vpc:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api1_listener/ECSGroup/Resource
  LBapi2listener9434057D:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi2listenerECSGroup8098F78C
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 3000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api2_listener/Resource
  LBapi2listenerECSGroup8098F78C:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: ip
      VpcId:
        Fn::ImportValue: Vpc:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api2_listener/ECSGroup/Resource
  LBapi3listenerC7F2EA36:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi3listenerECSGroup36DADFA3
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 4000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api3_listener/Resource
  LBapi3listenerECSGroup36DADFA3:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: ip
      VpcId:
        Fn::ImportValue: Vpc:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api3_listener/ECSGroup/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.29.0,@aws-cdk/assets=0.28.0,@aws-cdk/assets-docker=0.28.0,@aws-cdk/aws-apigateway=0.28.0,@aws-cdk/aws-applicationautoscaling=0.28.0,@aws-cdk/aws-autoscaling=0.28.0,@aws-cdk/aws-autoscaling-common=0.28.0,@aws-cdk/aws-certificatemanager=0.28.0,@aws-cdk/aws-cloudformation=0.28.0,@aws-cdk/aws-cloudwatch=0.28.0,@aws-cdk/aws-codedeploy-api=0.28.0,@aws-cdk/aws-ec2=0.28.0,@aws-cdk/aws-ecr=0.28.0,@aws-cdk/aws-ecs=0.28.0,@aws-cdk/aws-elasticloadbalancingv2=0.28.0,@aws-cdk/aws-events=0.28.0,@aws-cdk/aws-iam=0.28.0,@aws-cdk/aws-kms=0.28.0,@aws-cdk/aws-lambda=0.28.0,@aws-cdk/aws-logs=0.28.0,@aws-cdk/aws-route53=0.28.0,@aws-cdk/aws-s3=0.28.0,@aws-cdk/aws-s3-notifications=0.28.0,@aws-cdk/aws-servicediscovery=0.28.0,@aws-cdk/aws-sns=0.28.0,@aws-cdk/aws-sqs=0.28.0,@aws-cdk/cdk=0.28.0,@aws-cdk/cx-api=0.28.0,@aws-cdk/region-info=0.28.0,jsii-runtime=node.js/v11.2.0
Outputs:
  LBLoadBalancerArn4723B1BD:
    Value:
      Ref: LB8A12904C
    Export:
      Name: NLB:LBLoadBalancerArn4723B1BD
  ExportsOutputRefLBapi1listenerECSGroupB9F61AC8C200B214:
    Value:
      Ref: LBapi1listenerECSGroupB9F61AC8
    Export:
      Name: NLB:ExportsOutputRefLBapi1listenerECSGroupB9F61AC8C200B214
  ExportsOutputRefLBapi2listenerECSGroup8098F78C20773358:
    Value:
      Ref: LBapi2listenerECSGroup8098F78C
    Export:
      Name: NLB:ExportsOutputRefLBapi2listenerECSGroup8098F78C20773358
  ExportsOutputRefLBapi3listenerECSGroup36DADFA3C4AB8818:
    Value:
      Ref: LBapi3listenerECSGroup36DADFA3
    Export:
      Name: NLB:ExportsOutputRefLBapi3listenerECSGroup36DADFA3C4AB8818
